{
 "title": "Home Office",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Temperature",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 0 },
   "format": "celsius",
   "valueName": "avg",
   "targets": [
    { "expr": "temperature_celsius" }
   ]
  },
  {
   "title": "Humidity",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 7, "x": 5, "y": 0 },
   "format": "humidity",
   "valueName": "avg",
   "targets": [
    { "expr": "humidity_percent" }
   ]
  },
  {
   "title": "CO2",
   "type": "singlestat",
   "description": "Range is 400 to 60.000 ppm",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "format": "ppm",
   "valueName": "avg",
   "targets": [
    { "expr": "co2" }
   ]
  },
  {
   "title": "TVOC",
   "type": "singlestat",
   "description": "Total Volatile Organic Compounds",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "format": "ppm",
   "valueName": "avg",
   "targets": [
    { "expr": "tvoc" }
   ]
  },
  {
   "title": "Temperature over Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "temperature_celsius", "legendFormat": "Thomas Arbeitsplatz" }
   ]
  },
  {
   "title": "Humidity over Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    { "expr": "humidity_percent", "legendFormat": "Thomas Arbeitsplatz" }
   ]
  },
  {
   "title": "CO2 over Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "ppm" }
   ],
   "targets": [
    { "expr": "co2", "legendFormat": "Thomas Arbeitsplatz" }
   ]
  }
 ]
}